---
# This playbook will install mysql and create db user and give permissions.

#- name: Install Mysql package
  yum: name={{ item }} state=installed
  with_items:
   - mysql-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Install MySQL package
  apt: name=mysql-server state=present update_caches=yes

- name: Install python-mysqldb
  apt: name=python-mysqldb state=present

- name: Create Mysql configuration file
  template: src=my.cnf dest=/etc/mysql/conf.d/my.cnf
  notify:
    - restart mysql

- name: Start MySQL service
  service: name=mysql state=started enabled=true

- name: Insert iptables rule
  lineinfile: 
    path: /etc/iptables/rules.v4
    state: present 
    regexp: "{{ mysql_port }}"
    insertafter: "^:OUTPUT " 
    line: "-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
  notify: restart iptables

- name: Create Application Database
  mysql_db: name {{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
