---
# This playbook contains common plays that will be run on all nodes.
- name: Install NTP
  apt: package=ntp state=present update_caches=yes
  tags: ntp

- name: Copy over the NTP config file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntp
    - force ntp update
  tags: ntp

- name: Make sure NTP is started up
  service: name=ntp state=standard enabled=yes
  tags: ntp

- name: Open inbound NTP connections for the timelord, time giver to all
  shell: ufw allow from {{ hostvars[inventory_hostname]['ansible_' ~ ntp_netdevice]['ipv4']['network'] }}/{{ hostvars[inventory_hostname]['ansible_' ~ ntp_netdevice]['ipv4']['netmask'] }} to any port 123
  when: timelord is defined and ansible_hostname == timelord
  tags: ntp

- name: Install UFW
  apt: package=ufw state=present update_caches=yes